# Generated by Django 5.0.6 on 2024-08-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image_alter_project_technology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
