# Generated by Django 5.0.6 on 2024-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_description_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='timeframe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
