# Generated by Django 5.0.6 on 2024-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Hello, World!', max_length=200)),
                ('about_me_title', models.CharField(default='About me', max_length=100)),
                ('about_me_text', models.TextField(default='Hi! Welcome to my website! My name is Jason Qin, and I am currently studying Computer Science and Economics at Columbia University. Feel free to poke around and leave feedback!')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots/')),
            ],
        ),
    ]
